name: Run ESLint on changed files
description: Run ESLint on all changed files
author: jackton1
inputs:
  token:
    description: '[GITHUB\_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow) or a repo scoped [Personal Access Token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)'
    required: true
    default: ${{ github.token }}
  all_files:
    description: 'Run [ESlint](https://eslint.org/) on all matching files'
    required: false
    default: false
  config_path:
    description: '[ESlint](https://eslint.org/) [configuration file](https://eslint.org/docs/user-guide/configuring/)'
    required: false
    default: '.eslintrc'
  ignore_path:
    description: '[ESlint](https://eslint.org/) [ignore file](https://eslint.org/docs/user-guide/configuring/ignoring-code)'
    required: false
    default: ''
  file_extensions:
    description: List of file extensions to watch for changes and run [ESlint](https://eslint.org/) against
    required: false
    default: |
      **/*.ts
      **/*.tsx
      **/*.js
      **/*.jsx
  extra_args:
    description: Extra arguments passed to [ESlint](https://eslint.org/docs/user-guide/command-line-interface)
    required: false
    default: ''
  reporter:
    description: |
      Reporter of reviewdog command [github-check, github-pr-review].
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    required: false
    default: 'github-pr-review'
  filter_mode:
    description: Filtering mode for the reviewdog command [added, diff_context, file, nofilter].
    required: false
    default: 'added'
  skip_annotations:
    description: Skip applying reviewdog check annotations.
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.13.1
    - name: Run glob excluding files in the ignore_path
      uses: tj-actions/glob@v7.4
      id: eslint-glob
      with:
        files: |
          ${{ inputs.file_extensions }}
        excluded-files-from-source-file: ${{ inputs.ignore_path }}
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v17.2
      with:
        files: ${{ steps.eslint-glob.outputs.paths }}
        files_separator: " "
    - name: Run eslint on changed files
      run: |
        # Run eslint on changed files
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: eslint-changed-files
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_SHA: ${{ github.sha }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_ALL_FILES: ${{ inputs.all_files }}
        INPUT_CONFIG_PATH: ${{ inputs.config_path }}
        INPUT_IGNORE_PATH: ${{ inputs.ignore_path }}
        INPUT_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        INPUT_EXTRA_ARGS: ${{ inputs.extra_args }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_SKIP_ANNOTATIONS: ${{ inputs.skip_annotations }}

branding:
  icon: check-square
  color: white
