name: Run eslint on changed files
description: Run ESLint on JavaScript files
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  all_files:
    description: 'Run eslint on all matching files'
    required: false
  config_path:
    description: Eslint configuration path
    required: false
    default: '.eslintrc'
  ignore_path:
    description: Eslint ignore path
    required: false
    default: ''
  extensions:
    description: Comma separated list of extensions
    required: false
    default: 'ts,tsx,js,jsx'
  extra_args:
    description: Eslint extra arguments
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: check-square
  color: white
