name: Run eslint on changed files
description: Run ESLint on JavaScript files
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  all_files:
    description: 'Run eslint on all matching files'
    required: false
  config_path:
    description: Eslint configuration path
    required: false
    default: '.eslintrc'
  ignore_path:
    description: Eslint ignore path
    required: false
    default: ''
  extensions:
    description: Comma separated list of extensions
    required: false
    default: 'ts,tsx,js,jsx'
  extra_args:
    description: Eslint extra arguments
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.13.0
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: eslint-changed-files
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_SHA: ${{ github.sha }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_ALL_FILES: ${{ inputs.all_files }}
        INPUT_CONFIG_PATH: ${{ inputs.config_path }}
        INPUT_IGNORE_PATH: ${{ inputs.ignore_path }}
        INPUT_EXTENSIONS: ${{ inputs.extensions }}
        INPUT_EXTRA_ARGS: ${{ inputs.extra_args }}

branding:
  icon: check-square
  color: white
